version: '3.8'

services:
  # MySQL Database (Production)
  mysql:
    image: mysql:8.0
    container_name: wp_mysql_prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - wordpress_network
    secrets:
      - mysql_root_password
      - mysql_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=512M
      --max-connections=200
      --innodb-log-file-size=256M
      --query-cache-size=64M
      --query-cache-type=1

  # WordPress Application (Production)
  wordpress:
    image: wordpress:latest
    container_name: wp_app_prod
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${WORDPRESS_PORT:-80}:80"
    environment:
      # Database Configuration
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_password
      
      # WordPress Configuration
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX:-wp_}
      WORDPRESS_DEBUG: false
      
      # Production Configuration
      WORDPRESS_CONFIG_EXTRA: |
        // WordPress URLs para Producción
        define('WP_HOME', '${WORDPRESS_URL}');
        define('WP_SITEURL', '${WORDPRESS_URL}');
        
        // Production Performance Settings
        ini_set('memory_limit', '512M');
        ini_set('max_execution_time', '300');
        ini_set('max_input_vars', '3000');
        
        // Security Settings
        define('DISALLOW_FILE_EDIT', true);
        define('DISALLOW_FILE_MODS', true);
        define('WP_DEBUG', false);
        define('WP_DEBUG_LOG', false);
        define('WP_DEBUG_DISPLAY', false);
        
        // Cache Settings
        define('WP_CACHE', true);
        define('WP_POST_REVISIONS', 3);
        define('AUTOSAVE_INTERVAL', 300);
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress/themes:/var/www/html/wp-content/themes:ro
      - ./wordpress/plugins:/var/www/html/wp-content/plugins:ro
      - ./wordpress/uploads:/var/www/html/wp-content/uploads
    networks:
      - wordpress_network
      - web_gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`andessuyo.pe`) || Host(`www.andessuyo.pe`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=letsencrypt"
      - "traefik.http.routers.wordpress.service=wordpress"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
      - "traefik.http.middlewares.wordpress-redirect.redirectregex.regex=^https://www.andessuyo.pe/(.*)"
      - "traefik.http.middlewares.wordpress-redirect.redirectregex.replacement=https://andessuyo.pe/$${1}"
      - "traefik.http.routers.wordpress.middlewares=wordpress-redirect"
    secrets:
      - mysql_password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/wp-admin/install.php"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  wordpress_network:
    driver: bridge
  web_gateway:
    external: true

secrets:
  mysql_root_password:
    external: true
  mysql_password:
    external: true