services:
  # MySQL Database
  mysql:
    image: mariadb:10.11
    container_name: wp_mysql
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - wordpress_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # WordPress Application
  wordpress:
    image: wordpress:latest
    container_name: wp_app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${WORDPRESS_PORT:-8080}:80"
    environment:
      # Database Configuration
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
        

      # WordPress Configuration
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX:-wp_}
      WORDPRESS_DEBUG: ${WP_DEBUG:-false}

      # WordPress URLs
      WORDPRESS_CONFIG_EXTRA: |
        // apagando modo debug
        define('WP_DEBUG', false);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);

        // WordPress URLs
        define('WP_HOME', '${WORDPRESS_URL:-http://localhost:8080}');
        define('WP_SITEURL', '${WORDPRESS_URL:-http://localhost:8080}');
        
        // Performance Settings
        ini_set('memory_limit', '256M');
        ini_set('max_execution_time', '120');
        ini_set('max_input_vars', '2000');
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress:/var/www/html/wp-content
    networks:
      - wordpress_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/wp-admin/install.php"]
      interval: 30s
      timeout: 10s
      retries: 5

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: wp_phpmyadmin
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - wordpress_network

volumes:
  mysql_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  wordpress_network:
    driver: bridge
  mysql_password:
    external: true